version: "3.8"

services:
  rest-api:
    container_name: rest-api
    image: rest-api:latest
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=8080
    ports:
      - "8080:8080"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 700M
      restart_policy:
        condition: on-failure
    depends_on:
      - database
      - redis-server
    networks:
      - local-network
      
  database:
    container_name: database
    image: mongodb:latest
    ports:
      - "27017:27017"
    restart: on-failure
    networks:
      - local-network

  redis-server:
    container_name: redis-server
    image: redis:latest
    ports:
      - "6379:6379"
    restart: on-failure
    networks:
      - local-network

networks:
  local-network:
    name: local-network
    driver: bridge