# fly.toml app configuration file generated for level-up on 2023-05-25T10:12:17-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "level-up"
primary_region = "gru"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[services]]
  protocol = "tcp"
  internal_port = 8000

  [[services.ports]]
    port = 8000
    handlers = ["http"]
