apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: spring-api
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-api
spec:
  replicas: 2
  selector:
    matchExpressions:
      - { key: app, operator: In, values: [spring-api] }
  template:
    metadata:
      labels:
        app: spring-api
        tier: api
    spec:
      containers:
        - name: spring-api
          image: spring-reactive:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"