version: "3.8"

services:
  next-api:
    container_name: next-api
    image: next-api:latest
    build:
      context: ../../
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=jdbc:postgresql://next-db:5432/postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - REDIS_URL=redis://redis:6379
      - PORT=8000
    ports:
      - "8000:8000"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 700M
      restart_policy:
        condition: on-failure
    depends_on:
      - next-db
      - redis-server
    networks:
      - next-network
      
  next-db:
    container_name: next-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=America/Sao_Paulo
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - next-network

  redis-server:
    container_name: redis-server
    image: redis:latest
    ports:
      - "6379:6379"
    restart: on-failure
    networks:
      - next-network

networks:
  next-network:
    name: next-network
    driver: bridge